### ISSUE TITLE
Colour setting change makes 'Business settings' tab raise null pointer exception

### ISSUE THREAD

**Issue by RobLW** [s3529120/septsem12017#22]
When a  business selects a theme, it is reset to default on logout.

### Machine details where discovered:
ProductName: 	Mac OS X
ProductVersion:	10.12.4
BuildVersion:	16E195

**commit c8d665ed07f374b0744433f3809e940dbfcda34a
branch master**

### Recreation steps:
* login as a business user. 
* navigate to business settings tab on dashboard
* select a new colour from dropdown
* save change
* navigate away from business settings page
* attempt to navigate back to business settings page

The account will have the default scheme and the business settings button will raise null pointer exception.

**Comment by RobLW** [comment]
## Exception raised:

_Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at businessHours.BusinessHoursView.updateView(BusinessHoursView.java:362)
	at businessHours.BusinessHoursView$7.handle(BusinessHoursView.java:166)
	at businessHours.BusinessHoursView$7.handle(BusinessHoursView.java:1)_

**Comment by RobLW** [comment]
## Exception raised when attempting to navigate back to business settings:
_Exception in thread "JavaFX Application Thread" 
java.lang.NullPointerException
	at businessHours.BusinessHoursView.updateView(BusinessHoursView.java:362)
	at booking.BookingsView$5.handle(BookingsView.java:136)
	at booking.BookingsView$5.handle(BookingsView.java:1)_

**Comment by RobLW** [comment]
Issue resolved by adding appropriate css files for each colour in colour enum
