### ISSUE TITLE
Attempting to modify roster causes PRIMARY KEY error

### ISSUE THREAD

**Issue by RobLW** [s3529120/septsem12017#35]
* Change a business' hours
* Select new roster times for an employee
* Click save changes
Following error is raised:
```
org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: Availability.Email, Availability.Day, Availability.StartTime)
	at org.sqlite.core.DB.newSQLException(DB.java:909)
	at org.sqlite.core.DB.newSQLException(DB.java:921)
	at org.sqlite.core.DB.execute(DB.java:825)
	at org.sqlite.core.DB.executeUpdate(DB.java:863)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:99)
	at utils.DatabaseController.runSQLUpdate(DatabaseController.java:77)
	at employee.AvailabilitiesController.addAvailability(AvailabilitiesController.java:195)
	at employee.EditAvailabilitiesView$9.handle(EditAvailabilitiesView.java:383)
	at employee.EditAvailabilitiesView$9.handle(EditAvailabilitiesView.java:1)
```

**Comment by s3529120** [comment]
Fixed with commit 5441c11
