### ISSUE TITLE
AddEmployeeTest: testAddEmp() Result Set closed error

### ISSUE THREAD

**Issue by RobLW** [s3529120/septsem12017#7]
Result set fails to remain open, during test execution.

```
        @Test
	public void testAddEmp(){
		//Can we double check this?
		DatabaseModel dbmod = new DatabaseModel();
		DatabaseController dbcont = new DatabaseController(dbmod);
		String sql,name="",num="",email="",add="",city="",state="",postc="";
		ResultSet res;

		EmployeeController econt = new EmployeeController();

		try{
			dbcont.createConnection();
			econt.addEmployee("John Smith", "0555 555 555","myemail@gmail.com","123 Fake Street", 
					"Melbourne", "Victoria", "3000");
			sql="SELECT * FROM EMPLOYEE WHERE name='John Smith';";
			dbcont.prepareStatement(sql);
			res = dbcont.runSQLRes();
			System.out.printf("\nRes collected\n");
			name = res.getString("Name");
			num = res.getString("ContactNo");
			email = res.getString("Email");
			System.out.printf("Name: %s\nContact No.: %s\nEmail: %s", name,num,email);
			
			sql="SELECT * FROM ADDRESS WHERE EmployeeEmail='myemail@gmail.com';";
			dbcont.prepareStatement(sql);
			res = dbcont.runSQLRes();
			
			add = res.getString("StreetAddress");
			city = res.getString("City");
			state = res.getString("State");
			postc = res.getString("PostCode");

			assertEquals(name,"John Smith");
			assertEquals(num,"0555 555 555");
			assertEquals(email,"myemail@gmail.com");
			assertEquals(add,"123 Fake Street");
			assertEquals(city,"Melbourne");
			assertEquals(state,"Victoria");
			assertEquals(postc,"3000");

		}catch(Exception e){
			fail("SQLException Error.\nTest Failure.\nStack Trace: ");
			e.printStackTrace();
		}
	}
```

**Comment by RobLW** [comment]
```
java.sql.SQLException: ResultSet closed
	at org.sqlite.core.CoreResultSet.checkOpen(CoreResultSet.java:69)
	at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:38)
	at org.sqlite.jdbc3.JDBC3ResultSet.getString(JDBC3ResultSet.java:443)
	at unitTests.AddEmployeeTest.testAddEmp(AddEmployeeTest.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by s3529120** [comment]
`dbcont.createConnection();
			econt.addEmployee("John Smith", "0555 555 555","myemail@gmail.com","123 Fake Street", 
					"Melbourne", "Victoria", "3000");`
Would be creating the issue ad the addEmployee() method opens and closes the connection itself.
If you swap those 2 lines around it should (in theory) fix the issue.

**Comment by RobLW** [comment]
Thanks. I'll have a look in a little bit and document what happens.

**Comment by RobLW** [comment]
Alright, so the tests succeed even with the result set close error.
Apparently the result set close error is expected and the way of doing ```res = dbcont.runSQLRes() ``` is not the correct way to get a result set as per: http://stackoverflow.com/a/1814443

**Comment by s3529120** [comment]
Technicallly it is correct to call ResultSet.next() whenever you wish to access data from the ResultSet, however it will generally work without doing so.
